name = "mycash-api"
main = "src/index.ts"
compatibility_date = "2025-03-01"

[vars]
# JWT_SECRET = ""
# HASHIDS_SALT = ""
# S3_ENDPOINT = ""
# S3_ACCESS_KEY = ""
# S3_SECRET_KEY = ""
# S3_BUCKET = ""
# S3_REGION = "auto"

[[d1_databases]]
binding = "DB"
database_name = "mycash"
database_id = "local"
migrations_dir = "../../packages/database/drizzle"
